sudo: required
services:
  - docker

before_install:
  - docker build -t discoveranirban/react-fib -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true discoveranirban/react-fib npm run test -- --coverage

after_success:
  - docker build -t discoveranirban/multi-client ./client 
  - docker build -t discoveranirban/multi-nginx ./nginx 
  - docker build -t discoveranirban/multi-server ./server 
  - docker build -t discoveranirban/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push discoveranirban/multi-client
  - docker push discoveranirban/multi-nginx
  - docker push discoveranirban/multi-server
  - docker push discoveranirban/multi-worker